### ISSUE TITLE
NN architectures

### ISSUE THREAD

**Issue by NoName115** [H00N24/IA080-classifiers-comparison#3]
Please add here any NN architecture that you found.

**Comment by lordmathis** [comment]
We can take some networks that have been successful on [MNIST](http://yann.lecun.com/exdb/mnist/) or some other well known datasets and just adjust the input layer based on the dataset.

**Comment by RusteeKuntz** [comment]
I also found [this chart](https://towardsdatascience.com/the-mostly-complete-chart-of-neural-networks-explained-3fb6f2367464) for inspiration, although I am unsure about the availability of existing implementations for the networks.
